apiVersion: v2
name: mcpserver
description: A Helm chart for deploying the alkfet MCP Server service
type: application
version: 0.0.1
appVersion: "0.0.1"
keywords:
  - mcpserver
  - mcp
  - modelcontextprotocol
home: https://github.com/zsoltsimon97/alkfet
sources:
  - https://github.com/zsoltsimon97/alkfet
